### ISSUE TITLE
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by qquuzhao** [skandlab/PUREE#4]
Dear contributors

Hi, I've found the PUREE article and got fastinated on this tool and I'm happy to use the tool.
I was trying to use my tumor RNAseq samples (just one sample)to estimate tumor purity using python api but the result is not give out.
return like this:
Traceback (most recent call last):
  File "puree_Test.py", line 4, in <module>
    purities_and_logs = p.get_output(fpkm_last.csv', 'HGNC')
  File "puree.py", line 195, in get_output
    id = file_output[0].json()['id']
  File "models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
![企业微信截图_20230810181603](https://github.com/skandlab/PUREE/assets/27476013/e6cf6f47-a491-440d-9796-9519ea9f9ca0)

Thank you!

**Comment by qquuzhao** [comment]
Dear contributors，
        when I use API website，it's tell me  my inputfile is not correct,but how I know what's wrong with my inputfile.
        
![企业微信截图_20230811142834](https://github.com/skandlab/PUREE/assets/27476013/c00db38c-1ee8-4d33-b1e5-cafc9fcdef4e)
[fpkm_puree.txt](https://github.com/skandlab/PUREE/files/12319053/fpkm_puree.txt)

        Looking forward to your reply！

**Comment by erevkov** [comment]
Hi, thank you for trying PUREE!

Regarding your first comment, we could not reproduce the JSONDecodeError error. Which version of Python are you using for the installation? 

Regarding the second comment, it does look like the number of genes in the matrix you provided might be too little. Is your matrix a result of a bulk RNA-seq pipeline (the data type which PUREE was developed for)? Do you think you could try running the method on an expression profile with more genes?

**Comment by SamuelMathieu-code** [comment]
Hi! I got the same error as @qquuzhao. I'm running it in a dedicated conda environment with python 3.8.19 (installation would not work with latest python version or latest within 3.9).

Here are the environment packages (conda list):
```
# packages in environment at [...]
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
ca-certificates           2024.7.2             h06a4308_0  
certifi                   2024.7.4                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
idna                      3.7                      pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
ncurses                   6.4                  h6a678d5_0  
numpy                     1.24.4                   pypi_0    pypi
openssl                   3.0.14               h5eee18b_0  
pandas                    1.5.3                    pypi_0    pypi
pip                       24.0             py38h06a4308_0  
puree                     0.1.0                    pypi_0    pypi
pyreadr                   0.5.2                    pypi_0    pypi
python                    3.8.19               h955ad1f_0  
python-dateutil           2.9.0.post0              pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.28.2                   pypi_0    pypi
setuptools                69.5.1           py38h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
tk                        8.6.14               h39e8969_0  
urllib3                   1.26.19                  pypi_0    pypi
wheel                     0.43.0           py38h06a4308_0  
xz                        5.4.6                h5eee18b_1  
zlib                      1.2.13               h5eee18b_1 
```

and my csv file is structured as follows (62700 ENSG ids):

```
,ENSG00000290825,ENSG00000223972,ENSG00000227232, ...
X1,0.328782,0.0,33.7558, ...
X2,0.384906,0.0,24.2996, ...
...
```
Thanks in advance,

Sam

**Comment by tanmay2893** [comment]
Hi,

Thank you for bringing this matter to our attention. We have resolved the library conflicts as identified. However, we were unable to replicate the 504 error you encountered. Could you please let us know if you continue to experience any issues following our recent update?
